version: '3.4'

services:
  spot_back:
    build:
      context: .
      dockerfile: SPOTService/Dockerfile
    networks:
      - postgres
  spot_front:
    build:
      context: .
      dockerfile: react-spot-frontend/Dockerfile
    ports:
      - 3000:3000
    networks:
      - postgres
  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_DB: "SPOT"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - 5434:5432
    volumes:
      - ../2. Init Database:/docker-entrypoint-initdb.d
      - habrdb-data:/var/lib/postgresql/data
    networks:
      - postgres

volumes:
  habrdb-data:
networks:
  postgres:
    driver: bridge